import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return (
    <main id="main-content"><section className="legal-hero"><div className="shell"><span className="eyebrow light">Privacy</span><h1>Your privacy begins before your first appointment.</h1></div></section><section className="section-pad"><article className="shell legal-content"><p className="legal-updated">Draft website privacy notice · July 2026</p><h2>Information this website handles</h2><p>The public website provides contact links and a guided appointment-request tool. The current appointment tool prepares a message for you to send through WhatsApp; it does not store your form entries in a website database.</p><h2>Contacting the centre</h2><p>If you contact Kindred Path by telephone, email or WhatsApp, the information you provide is handled through that service and by the centre for the purpose of responding to your enquiry and coordinating care.</p><h2>Sensitive medical information</h2><p>Please do not submit detailed medical information through a general website enquiry or WhatsApp appointment request. Medical history should be discussed through the centre’s appropriate confidential clinical process.</p><h2>Website analytics and cookies</h2><p>This build does not intentionally place marketing-tracking cookies. If analytics, advertising or embedded third-party services are added later, this notice and the consent experience should be updated before launch.</p><h2>Your choices</h2><p>You may ask the centre what information it holds about your enquiry and request correction where appropriate. Clinical records may be subject to separate medical-record obligations.</p><h2>Contact</h2><p>For privacy questions, email <a href="mailto:Kindredpathifm@gmail.com">Kindredpathifm@gmail.com</a> or call <a href="tel:+2349132347955">+234 913 234 7955</a>.</p><div className="legal-warning"><strong>Launch requirement</strong><p>This draft should be reviewed and approved by Kindred Path management or its legal/privacy adviser before the website replaces the current live site.</p></div></article></section></main>
  );
}
