import type { Article } from "./content";

const coreSources = {
  who: { label: "World Health Organization: Infertility", url: "https://www.who.int/news-room/fact-sheets/detail/infertility" },
  hfeaIvf: { label: "HFEA: In vitro fertilisation", url: "https://www.hfea.gov.uk/treatments/explore-all-treatments/in-vitro-fertilisation-ivf/" },
  nhsIvf: { label: "NHS: IVF", url: "https://www.nhs.uk/tests-and-treatments/ivf/" },
  nhsIui: { label: "NHS: Intrauterine insemination", url: "https://www.nhs.uk/tests-and-treatments/intrauterine-insemination-iui/" },
  hfeaEgg: { label: "HFEA: Egg freezing", url: "https://www.hfea.gov.uk/treatments/fertility-preservation/egg-freezing/" },
  asrmMale: { label: "AUA/ASRM: Male infertility guideline", url: "https://www.asrm.org/practice-guidance/practice-committee-documents/diagnosis-and-treatment-of-infertility-in-men-auaasrm-guideline-part-i-2020/" },
  whoPcos: { label: "World Health Organization: PCOS", url: "https://www.who.int/news-room/fact-sheets/detail/polycystic-ovary-syndrome" },
  whoEndo: { label: "World Health Organization: Endometriosis", url: "https://www.who.int/news-room/fact-sheets/detail/endometriosis" },
  hfeaRates: { label: "HFEA: Choose a fertility clinic", url: "https://www.hfea.gov.uk/choose-a-fertility-clinic/" },
};

export const articles: Article[] = [
  {
    slug: "ivf-in-lagos-what-to-expect",
    category: "IVF in Lagos",
    title: "IVF in Lagos: what to expect before your first cycle",
    excerpt: "A practical, no-hype guide to consultation, testing, timelines, costs and questions to ask before IVF treatment.",
    read: "9 min read",
    description: "Considering IVF in Lagos? Understand the IVF process, preparation, costs to clarify, risks and questions to ask a fertility clinic.",
    keywords: ["IVF in Lagos", "IVF clinic Lagos", "fertility centre Ikeja", "IVF treatment Nigeria"],
    sections: [
      { heading: "Begin with the reason IVF is being discussed", paragraphs: ["IVF can be considered for many different fertility situations, including tubal problems, some male-factor concerns, ovulation disorders, endometriosis, unexplained infertility or previous treatment that has not worked. The fact that IVF is available does not mean it is automatically the best first step for everyone.", "At consultation, ask the specialist to explain the working diagnosis, what information is still missing and why IVF is more appropriate than timed intercourse, ovulation treatment, IUI, surgery, preservation or further assessment. A good recommendation should connect your findings to the proposed treatment."] },
      { heading: "Understand the sequence, not just the procedure", paragraphs: ["An IVF cycle usually involves preparation, ovarian stimulation, monitoring scans, egg collection, laboratory fertilisation, embryo development and either embryo transfer or freezing. Treatment can change along the way because response, safety and embryo development cannot be known in advance."], bullets: ["Who manages questions outside appointments?", "How often is monitoring likely to happen?", "Where are egg collection and laboratory work performed?", "What happens if response is lower or higher than expected?", "When are decisions about transfer or freezing made?"] },
      { heading: "Ask for a complete cost conversation", paragraphs: ["A package price may not include every medicine, test, scan, anaesthetic fee, laboratory technique, storage fee or later frozen-embryo transfer. Ask for a written estimate that separates essential treatment from optional add-ons. Also ask which costs may change after results or response are known.", "Price matters, but the cheapest headline can become expensive if key elements are excluded. Clear cancellation, refund, storage and repeat-cycle policies are part of informed financial consent."] },
      { heading: "Success needs context", paragraphs: ["Do not rely on one large percentage. Ask whether a figure refers to pregnancy or live birth, per transfer or per started cycle, which age group, which year and whether donor eggs are included. Your personal outlook depends on factors that a website cannot fully capture."] },
      { heading: "Prepare for the emotional workload", paragraphs: ["IVF involves waiting and uncertainty as well as appointments. Decide who you want to tell, how work absences may be handled and who you can contact for support. Counselling is not only for crisis; it can help before treatment begins."] },
    ],
    faq: [{ question: "How long does IVF take?", answer: "An individual cycle often takes several weeks, but preparation, testing, scheduling, freezing or additional treatment can extend the overall timeline." }, { question: "Does IVF guarantee pregnancy?", answer: "No. Eggs, fertilisation, embryo development, implantation and live birth cannot be guaranteed." }, { question: "Should both partners attend the first consultation?", answer: "Where two partners are involved, both histories and relevant assessment can make planning more efficient." }],
    sources: [coreSources.hfeaIvf, coreSources.nhsIvf, coreSources.who],
  },
  {
    slug: "ivf-cost-in-nigeria-questions-to-ask",
    category: "Planning treatment",
    title: "IVF cost in Nigeria: the questions behind the price",
    excerpt: "Why IVF quotes differ and how to compare medicines, tests, laboratory services, storage and follow-up fairly.",
    read: "8 min read",
    description: "Learn what affects IVF cost in Nigeria and how to compare fertility clinic quotations without being misled by a headline package price.",
    keywords: ["IVF cost in Nigeria", "IVF price Lagos", "cost of IVF in Lagos", "affordable IVF Nigeria"],
    sections: [
      { heading: "There is no single universal IVF price", paragraphs: ["IVF cost varies because patients do not all need the same medication, investigation, laboratory method or number of treatment stages. A clinic may quote a core cycle while another includes selected scans, anaesthesia or laboratory work. Comparing only the largest number on an advert can therefore be misleading."] },
      { heading: "Ask what the quote includes", paragraphs: ["Request a written breakdown before paying. It should be clear whether consultation, blood tests, scans, medicines, egg collection, anaesthesia, semen preparation, fertilisation, embryo culture, transfer, pregnancy testing and follow-up are included."], bullets: ["Are medicines included or estimated separately?", "Are ICSI or other laboratory techniques included only when needed?", "Is embryo freezing included?", "What are the annual storage fees?", "Does a later frozen-embryo transfer have a separate fee?", "What happens financially if a cycle is cancelled?"] },
      { heading: "Optional add-ons deserve separate scrutiny", paragraphs: ["An add-on should be named precisely. Ask what evidence shows it improves the outcome that matters to you, whether it is recommended because of a specific finding and what the risks and alternatives are. “Advanced” does not automatically mean necessary."] },
      { heading: "Plan for indirect costs", paragraphs: ["Transport, time away from work, accommodation, repeat tests and support can affect the real cost of treatment. Patients travelling from outside Lagos may benefit from asking which appointments can be online and which must be in person."] },
      { heading: "Good financial consent is clinical care", paragraphs: ["You should understand likely costs before starting, but some uncertainty may remain until response and results are known. A responsible clinic explains what is fixed, what may change and when you will be asked to decide."] },
    ],
    faq: [{ question: "Why do IVF prices differ between patients?", answer: "Medication response, investigations, laboratory methods, storage and whether further treatment is required can all change cost." }, { question: "Is the lowest IVF package always the cheapest overall?", answer: "Not necessarily. Excluded medicines, tests, storage or transfer fees can substantially change the final amount." }],
    sources: [coreSources.hfeaIvf, coreSources.nhsIvf],
  },
  {
    slug: "when-to-see-a-fertility-specialist",
    category: "Getting started",
    title: "When should you see a fertility specialist?",
    excerpt: "A practical guide to timing, age, irregular cycles, male concerns and situations where waiting may not be helpful.",
    read: "7 min read",
    description: "Know when to see a fertility specialist in Lagos, including after 12 months of trying, age 35+, irregular cycles or known reproductive concerns.",
    keywords: ["when to see fertility specialist", "fertility doctor Lagos", "trying to conceive Nigeria", "fertility consultation Ikeja"],
    sections: [
      { heading: "The familiar 12-month guide", paragraphs: ["Infertility is commonly defined as not achieving pregnancy after 12 months or more of regular unprotected intercourse. That definition is useful for public health, but it is not a rule that everyone must wait exactly one year before asking for advice."] },
      { heading: "Age changes the timing conversation", paragraphs: ["Fertility declines with age, particularly because egg quantity and quality change. People aged 35 or older are often advised to seek assessment after about six months of trying, while those over 40 may benefit from an earlier conversation. Individual history still matters."] },
      { heading: "Reasons to seek advice earlier", paragraphs: ["Earlier consultation may be appropriate when there is information that could change the plan."], bullets: ["Very irregular or absent periods", "Known endometriosis, pelvic infection or tubal disease", "Previous ovarian, uterine, pelvic or testicular surgery", "Recurrent pregnancy loss", "Cancer treatment or another fertility-affecting medical treatment", "Erection, ejaculation or known semen concerns", "A plan to preserve fertility before delaying family building"] },
      { heading: "Both partners should be considered", paragraphs: ["Where a couple is trying together, assessment should not begin with the assumption that one partner is the cause. A parallel history and early semen analysis can reduce delays and unnecessary treatment."] },
      { heading: "Consultation does not commit you to IVF", paragraphs: ["Seeing a specialist means gathering information. The next step could be reassurance, cycle guidance, a focused test, treatment of a known condition, IUI, IVF, fertility preservation or simply a plan for when to review again."] },
    ],
    faq: [{ question: "Do I need a referral?", answer: "Requirements vary by clinic. Kindred Path accepts appointment enquiries directly through its contact and booking routes." }, { question: "Can I attend before one year of trying?", answer: "Yes, particularly when age, symptoms, medical history or male fertility concerns make earlier assessment sensible." }],
    sources: [coreSources.who, { label: "CDC: Infertility FAQs", url: "https://www.cdc.gov/reproductive-health/infertility-faq/index.html" }],
  },
  {
    slug: "semen-analysis-in-lagos-what-results-mean",
    category: "Male fertility",
    title: "Semen analysis in Lagos: what the test can and cannot tell you",
    excerpt: "How to prepare, what the laboratory measures, why results vary and when repeat testing may be useful.",
    read: "8 min read",
    description: "Preparing for semen analysis in Lagos? Understand sperm concentration, motility, morphology, sample instructions and next steps.",
    keywords: ["semen analysis Lagos", "sperm test Lagos", "male fertility test Nigeria", "semen analysis Ikeja"],
    sections: [
      { heading: "Semen analysis is a starting point", paragraphs: ["A semen analysis examines several characteristics of an ejaculate. Common parameters include volume, sperm concentration, total number, movement and shape. The result contributes to fertility assessment but does not independently prove that a person is fertile or infertile."] },
      { heading: "Preparation affects usefulness", paragraphs: ["Follow the laboratory’s instructions about abstinence, collection container, hygiene, location and how quickly a sample must arrive. Tell the clinician about recent fever, illness, medication or difficulty collecting the complete sample, because these details can affect interpretation."], bullets: ["Use only the approved container", "Avoid unapproved lubricants", "Record if any of the sample was lost", "Keep to the requested delivery time", "Ask before stopping any medicine"] },
      { heading: "Why one result may not be final", paragraphs: ["Semen parameters naturally vary. Illness, timing, collection and biological variation can influence results. A clinician may recommend another sample after an appropriate interval, especially when a result is unexpected or treatment decisions depend on it."] },
      { heading: "Interpret the whole pattern", paragraphs: ["Do not focus on one highlighted number. The combination of results, reproductive history, examination and sometimes hormonal, genetic or imaging assessment matters. A male reproductive specialist may be appropriate for severe or persistent abnormalities."] },
      { heading: "Male health matters beyond fertility", paragraphs: ["Some semen abnormalities may be associated with wider reproductive or general-health issues. Assessment is an opportunity to review medication, tobacco or drug exposure, anabolic steroids, heat, infection history, sexual function and relevant medical conditions without blame."] },
    ],
    faq: [{ question: "Can I do a semen analysis at home?", answer: "Collection arrangements vary. The sample must follow the laboratory’s method and timing requirements, so confirm before collecting." }, { question: "Does an abnormal result mean IVF is required?", answer: "No. Next steps depend on the severity, repeat findings, both partners’ assessment and the underlying cause." }],
    sources: [coreSources.asrmMale, { label: "ASRM: The role of male reproductive assessment", url: "https://www.asrm.org/asrm-academy/asrm-academy-on-the-go/asrmed-talks/a-few-good-sperm/" }],
  },
  {
    slug: "iui-vs-ivf-differences",
    category: "Treatment options",
    title: "IUI vs IVF: understanding the difference before choosing",
    excerpt: "How IUI and IVF differ in process, suitability, monitoring, laboratory involvement, cost and decision-making.",
    read: "8 min read",
    description: "Compare IUI and IVF treatment, including how each works, who may be suitable and which questions to ask your fertility specialist.",
    keywords: ["IUI vs IVF", "IUI treatment Lagos", "IVF treatment Lagos", "fertility treatment Nigeria"],
    sections: [
      { heading: "The central difference", paragraphs: ["With IUI, prepared sperm are placed directly into the uterus around ovulation and fertilisation still needs to happen inside the body. With IVF, eggs are collected and fertilised in a laboratory before an embryo may be transferred to the uterus."] },
      { heading: "IUI is simpler, but suitability is narrower", paragraphs: ["IUI generally involves less medication, no egg collection and less laboratory work than IVF. It may be considered when fallopian tubes are open, ovulation and sperm factors are suitable, or donor sperm is being used. It may offer limited benefit in severe tubal or male-factor problems."] },
      { heading: "IVF offers more laboratory information", paragraphs: ["IVF allows the team to observe fertilisation and embryo development. It can address a wider range of fertility factors, but requires more medication, monitoring, procedures, cost and decisions about embryos."], bullets: ["Why is one option being recommended?", "How many attempts would be reasonable before reviewing?", "What would make the team change strategy?", "Which risks apply to medication and multiple pregnancy?", "What are the full costs of each pathway?"] },
      { heading: "Age and time can affect the decision", paragraphs: ["When time is clinically important, repeating a lower-intervention treatment with a low expected benefit may not be the best use of time. On the other hand, IVF should not be recommended simply because it is available. The expected benefit and trade-offs need to be individualised."] },
      { heading: "A decision is more than a success percentage", paragraphs: ["Consider invasiveness, diagnosis, time, finances, emotional capacity, number of visits and what you would do if the first attempt is unsuccessful. Ask for a review point before starting."] },
    ],
    faq: [{ question: "Is IUI always tried before IVF?", answer: "No. The appropriate order depends on age, diagnosis, tube status, semen factors, previous treatment and other circumstances." }, { question: "Is IUI painless?", answer: "Many people experience little discomfort, but experiences vary and medication or monitoring may still be involved." }],
    sources: [coreSources.nhsIui, coreSources.hfeaIvf, coreSources.nhsIvf],
  },
  {
    slug: "egg-freezing-in-nigeria-guide",
    category: "Fertility preservation",
    title: "Egg freezing in Nigeria: a decision guide for the future",
    excerpt: "What egg freezing involves, why age matters, what it cannot guarantee and the storage questions people often miss.",
    read: "9 min read",
    description: "Considering egg freezing in Nigeria? Learn about timing, ovarian stimulation, egg collection, storage and realistic expectations.",
    keywords: ["egg freezing Nigeria", "egg freezing Lagos", "fertility preservation Lagos", "freeze eggs Nigeria"],
    sections: [
      { heading: "What egg freezing does", paragraphs: ["Egg freezing collects and stores unfertilised eggs for possible use in future fertility treatment. It may be considered before medical treatment that could affect fertility or for personal timing reasons. It preserves a possibility, not a guaranteed future baby."] },
      { heading: "Why age at freezing matters", paragraphs: ["Egg number and quality change with age. Population data show that age at freezing influences future prospects, but age is not the only factor and no exact number of stored eggs guarantees an outcome. A consultation should discuss ovarian-reserve information without presenting it as a direct fertility score."] },
      { heading: "The treatment resembles the first part of IVF", paragraphs: ["Medication encourages several eggs to develop. Monitoring tracks response. Eggs are collected during a procedure, and mature eggs are frozen. Future use would usually require thawing, fertilisation in a laboratory and embryo transfer."], bullets: ["How many cycles might be considered?", "Which costs relate to medication, collection and storage?", "What is the annual storage process?", "How are eggs used in the future?", "What happens if eggs are not used?"] },
      { heading: "Medical and personal reasons need different timelines", paragraphs: ["Cancer treatment or surgery can create urgency and requires coordination with the treating team. Elective preservation may allow more time to consider finances, relationships, beliefs and alternatives. In either case, ask what delaying a decision may change."] },
      { heading: "Plan for consent over many years", paragraphs: ["Long-term storage requires current contact details, fee arrangements and decisions about future use, donation or disposal. Ask how the clinic handles expired consent, loss of contact, incapacity or death, and request copies of signed documentation."] },
    ],
    faq: [{ question: "What is the best age to freeze eggs?", answer: "There is no single age for everyone, but age at freezing is an important factor. An individual consultation should discuss timing and realistic expectations." }, { question: "Does egg freezing stop biological ageing?", answer: "Stored eggs remain at the age they were frozen, but egg freezing does not stop other health or pregnancy-related changes over time." }],
    sources: [coreSources.hfeaEgg, { label: "HFEA: Egg freezing factsheet", url: "https://www.hfea.gov.uk/about-us/media-centre/egg-freezing-a-factsheet/" }],
  },
  {
    slug: "pcos-and-fertility",
    category: "Fertility health",
    title: "PCOS and fertility: what irregular ovulation means for conception",
    excerpt: "How PCOS can affect ovulation, which assessments may help and why treatment should be personalised.",
    read: "8 min read",
    description: "Understand PCOS and fertility, including irregular ovulation, assessment and fertility treatment options available in Lagos.",
    keywords: ["PCOS fertility treatment Lagos", "PCOS and infertility Nigeria", "irregular periods fertility"],
    sections: [
      { heading: "PCOS is common, and not one single experience", paragraphs: ["Polycystic ovary syndrome is a hormonal condition that may involve irregular or absent ovulation, higher androgen levels and characteristic ovarian findings. People can have different combinations of symptoms, and having polycystic-looking ovaries alone does not automatically establish the diagnosis."] },
      { heading: "Why conception may take longer", paragraphs: ["When ovulation is infrequent, there are fewer predictable opportunities for conception. PCOS can also be associated with metabolic factors that matter for long-term health and pregnancy planning. However, PCOS does not mean pregnancy is impossible."] },
      { heading: "Assessment should look beyond a scan", paragraphs: ["A clinician may review cycle history, symptoms, medications, weight and metabolic health, pregnancy history and blood tests. Where a couple is trying, semen factors and fallopian-tube considerations may still need assessment; PCOS should not become the assumed explanation for everything."], bullets: ["Track cycle patterns without relying only on an app", "Review medicines and supplements", "Ask which tests change treatment", "Include the other partner’s assessment where relevant"] },
      { heading: "Treatment follows the goal", paragraphs: ["Management for acne or cycle control is different from treatment aimed at pregnancy. Options may include lifestyle support, medication to induce ovulation, monitoring, IUI in selected circumstances or IVF when other factors or treatment history justify it."] },
      { heading: "Avoid blame and miracle claims", paragraphs: ["PCOS is not caused by a lack of effort. Be cautious of products promising to “cure” PCOS or guarantee ovulation. Sustainable health support and evidence-based fertility treatment should be individual and respectful."] },
    ],
    faq: [{ question: "Can someone with PCOS get pregnant naturally?", answer: "Yes, many do. The effect depends on ovulation, age, other fertility factors and individual circumstances." }, { question: "Does PCOS always require IVF?", answer: "No. Many people start with other management or ovulation-focused treatment when appropriate." }],
    sources: [coreSources.whoPcos, coreSources.who],
  },
  {
    slug: "endometriosis-and-fertility",
    category: "Fertility health",
    title: "Endometriosis and fertility: when pain and conception concerns overlap",
    excerpt: "How endometriosis may affect fertility and why age, symptoms, ovarian reserve and previous surgery all matter.",
    read: "9 min read",
    description: "Learn how endometriosis can affect fertility, when to seek assessment and how treatment decisions may include surgery, IUI or IVF.",
    keywords: ["endometriosis fertility Lagos", "endometriosis treatment Nigeria", "pelvic pain infertility"],
    sections: [
      { heading: "Endometriosis is more than painful periods", paragraphs: ["Endometriosis occurs when tissue similar to the uterine lining grows outside the uterus. Symptoms can include severe period pain, chronic pelvic pain, pain during sex, bowel or bladder symptoms and infertility. Some people have few symptoms despite significant disease, while others have severe pain with limited visible disease."] },
      { heading: "Fertility effects are not identical", paragraphs: ["Endometriosis may affect pelvic anatomy, inflammation, ovarian function or the environment around eggs and sperm. Yet diagnosis does not predict exactly whether or when an individual will conceive. Age, tubes, semen factors, ovarian reserve and previous treatment remain important."] },
      { heading: "Surgery is not automatically the first fertility treatment", paragraphs: ["Surgery may help pain, clarify anatomy or address selected findings, but ovarian surgery can also affect ovarian tissue. Decisions should consider symptoms, cyst size and appearance, age, ovarian reserve, previous surgery and whether assisted conception is planned."], bullets: ["What is the goal of surgery?", "Could surgery delay fertility treatment?", "How might ovarian reserve be affected?", "What are the alternatives?", "Should embryos or eggs be preserved first?"] },
      { heading: "When IVF may be discussed", paragraphs: ["IVF may be considered when tubes are affected, semen factors coexist, age or time matters, previous treatment has not worked, or other circumstances make it the more efficient pathway. It does not treat endometriosis pain itself."] },
      { heading: "Seek care that addresses both goals", paragraphs: ["Pain management and fertility planning sometimes require different priorities. Tell the clinician which matters most now and what previous treatment has changed. A coordinated plan can avoid repeated interventions that do not support the current goal."] },
    ],
    faq: [{ question: "Does endometriosis always cause infertility?", answer: "No. Many people with endometriosis conceive, while others need support. Individual assessment matters." }, { question: "Can a normal ultrasound exclude endometriosis?", answer: "No. Some forms may not be visible on routine ultrasound, and assessment depends on symptoms and specialist evaluation." }],
    sources: [coreSources.whoEndo, coreSources.hfeaIvf],
  },
  {
    slug: "fibroids-and-fertility",
    category: "Fertility health",
    title: "Fibroids and fertility: size is not the only question",
    excerpt: "Why location, cavity distortion, symptoms and treatment history matter when discussing fibroids and pregnancy.",
    read: "8 min read",
    description: "Understand fibroids and fertility, including which fibroid features may matter and questions to ask before surgery or IVF.",
    keywords: ["fibroids and fertility Nigeria", "fibroid treatment Lagos", "fibroids IVF"],
    sections: [
      { heading: "Fibroids are common", paragraphs: ["Fibroids are non-cancerous growths arising from the muscle of the uterus. Many people have fibroids and conceive without difficulty. The presence of a fibroid on a scan does not by itself prove that it is causing infertility."] },
      { heading: "Location may matter more than a headline size", paragraphs: ["Fibroids that distort the uterine cavity may be more relevant to implantation or pregnancy than some fibroids growing outward from the uterus. Number, location, growth pattern, symptoms and previous pregnancy history all contribute to the discussion."] },
      { heading: "Assessment should answer a specific question", paragraphs: ["Ultrasound may describe the uterus, ovaries and fibroids. Additional imaging or cavity assessment may be considered when results would change management. Ask the clinician to show which finding is relevant to the proposed fertility plan."], bullets: ["Does the fibroid distort the cavity?", "Could it affect egg collection or pregnancy?", "What symptoms is treatment expected to improve?", "What are the risks of surgery for future pregnancy?", "How long should conception or IVF wait after treatment?"] },
      { heading: "Removing every fibroid is not always helpful", paragraphs: ["Surgery can relieve symptoms or improve anatomy in selected cases, but it also brings recovery time, scar formation and other risks. The decision should weigh likely benefit against delay and procedure risk, especially when age or ovarian reserve makes time important."] },
      { heading: "Bring fertility and gynaecology planning together", paragraphs: ["If IVF is being considered, the fertility specialist and surgeon should agree on the purpose and timing of treatment. Patients should not have to navigate contradictory plans alone."] },
    ],
    faq: [{ question: "Can fibroids cause infertility?", answer: "Some fibroids may contribute, particularly when they affect the uterine cavity, but many people with fibroids conceive. Assessment should be individual." }, { question: "Must fibroids be removed before IVF?", answer: "No. The recommendation depends on location, symptoms, cavity effects, history and procedure risks." }],
    sources: [{ label: "MedlinePlus: Uterine diseases", url: "https://medlineplus.gov/uterinediseases.html" }, coreSources.who],
  },
  {
    slug: "fertility-after-40-options-and-questions",
    category: "Age and fertility",
    title: "Fertility after 40: options, timelines and honest questions",
    excerpt: "How age affects eggs and treatment statistics without reducing an individual to one number.",
    read: "9 min read",
    description: "Explore fertility after 40, including assessment, IVF, donor eggs, treatment timelines and how to interpret age-related success data.",
    keywords: ["fertility after 40 Nigeria", "IVF over 40 Lagos", "pregnancy after 40 fertility clinic"],
    sections: [
      { heading: "Age matters, but it is not the whole consultation", paragraphs: ["With increasing age, the number of available eggs and the proportion of eggs with chromosomal abnormalities change. This affects natural conception, miscarriage risk and IVF outcomes using a patient’s own eggs. The rate and timing differ between individuals, so assessment still matters."] },
      { heading: "Move from general statistics to a personal plan", paragraphs: ["A consultation may review cycle history, pregnancy history, ovarian-reserve information, uterus and tubes, semen factors, health conditions and how long you wish to try each option. Ovarian reserve tests help estimate response to stimulation; they do not directly declare whether natural pregnancy is possible."] },
      { heading: "Discuss time limits before treatment begins", paragraphs: ["Ask how many cycles or months would be reasonable before reviewing the strategy. A clear review point reduces the risk of continuing the same low-benefit approach without reflection."], bullets: ["What outcome does the clinic’s age-specific figure measure?", "Would using donor eggs materially change the discussion?", "What pregnancy-health review is recommended?", "What are the alternatives if response is low?", "How will emotional and financial limits be respected?"] },
      { heading: "Donor eggs may be part of the conversation", paragraphs: ["Donor-egg treatment can change age-related egg factors, but it introduces significant consent, screening, genetic, family and emotional questions. It should be discussed carefully, not presented as a casual backup plan."] },
      { heading: "Beware of anti-ageing promises", paragraphs: ["No supplement or procedure should be marketed as reversing reproductive age or guaranteeing egg quality. Ask emerging-treatment providers to specify the evidence, intended outcome, risks and cost, and seek an independent view when claims sound absolute."] },
    ],
    faq: [{ question: "Is pregnancy possible after 40?", answer: "Yes, but population-level chances and pregnancy risks change with age. Individual assessment and honest counselling are important." }, { question: "Does a normal AMH mean egg quality is normal?", answer: "No. AMH mainly helps estimate egg quantity and likely stimulation response; it does not directly measure egg quality." }],
    sources: [{ label: "HFEA: Fertility treatment trends and age", url: "https://www.hfea.gov.uk/about-us/publications/research-and-data/fertility-treatment-2024-trends-and-figures" }, coreSources.hfeaRates],
  },
  {
    slug: "recurrent-pregnancy-loss-next-steps",
    category: "Pregnancy loss",
    title: "After repeated pregnancy loss: questions for the next consultation",
    excerpt: "A compassionate guide to records, assessment, uncertainty and avoiding unsupported promises after miscarriage.",
    read: "8 min read",
    description: "Prepare for a fertility consultation after recurrent pregnancy loss with questions about assessment, records, treatment and emotional support.",
    keywords: ["recurrent miscarriage Lagos", "pregnancy loss fertility clinic Nigeria", "repeated miscarriage tests"],
    sections: [
      { heading: "Loss deserves care, not blame", paragraphs: ["Pregnancy loss can bring grief, fear and an urgent need for an explanation. Often, a single definite cause is not found. That uncertainty does not mean the loss was caused by something the patient did or failed to do."] },
      { heading: "Bring the timeline together", paragraphs: ["Collect scan reports, pregnancy-test dates, any laboratory or genetic results, treatment details and discharge summaries. A clear timeline helps the clinician distinguish confirmed pregnancies, gestational stage and whether a repeated pattern suggests focused assessment."] },
      { heading: "Testing should be purposeful", paragraphs: ["Depending on history, evaluation may consider uterine anatomy, selected hormonal or metabolic factors, antiphospholipid syndrome, parental chromosomes or pregnancy tissue testing. Not every available test is useful for every patient."], bullets: ["What question will this test answer?", "How would a positive or negative result change treatment?", "Is the test supported by guidelines?", "Could the result be uncertain or incidental?", "What will not be explained even after testing?"] },
      { heading: "Be cautious with broad immune panels and guarantees", paragraphs: ["Repeated loss can make expensive add-ons feel urgent. Ask whether an intervention improves live birth for people with your findings, what risks it brings and whether an independent specialist would recommend it. Testimonials are not a substitute for evidence."] },
      { heading: "Emotional follow-up is part of treatment", paragraphs: ["Future pregnancy may involve anxiety even when progress is medically reassuring. Ask what early-pregnancy follow-up is available, who to call with concerns and where counselling or loss support can be found."] },
    ],
    faq: [{ question: "Will testing always find a cause?", answer: "No. Some people receive a clear explanation while others do not, even after appropriate assessment." }, { question: "Does IVF prevent miscarriage?", answer: "Not in every situation. IVF may address particular fertility factors, but miscarriage can have many causes." }],
    sources: [coreSources.who, { label: "CDC: Infertility and pregnancy difficulty", url: "https://www.cdc.gov/reproductive-health/infertility-faq/index.html" }],
  },
  {
    slug: "preparing-for-fertility-consultation-checklist",
    category: "Patient checklist",
    title: "Fertility consultation checklist: 15 questions to take with you",
    excerpt: "A printable-style question list covering diagnosis, tests, treatment, costs, success data, risks and communication.",
    read: "7 min read",
    description: "Use this fertility consultation checklist to ask about diagnosis, tests, IVF costs, success rates, risks and next steps.",
    keywords: ["fertility consultation checklist", "questions to ask IVF clinic", "fertility appointment Lagos"],
    sections: [
      { heading: "Questions about the diagnosis", paragraphs: ["A consultation is more useful when you understand what is known, what is suspected and what remains uncertain."], bullets: ["What are the main possible reasons we have not conceived?", "Should both partners be assessed now?", "Which existing results are still useful?", "Which test would change the plan?", "What can we reasonably leave out?"] },
      { heading: "Questions about treatment", paragraphs: ["Ask the team to connect each recommendation to your assessment."], bullets: ["Why is this treatment appropriate for us?", "What are the alternatives, including waiting?", "What are the main risks and burdens?", "What would make you cancel or change the cycle?", "When will we review whether to continue?"] },
      { heading: "Questions about money", paragraphs: ["Request written information rather than relying on memory during an emotional appointment."], bullets: ["What is included in the quoted fee?", "Which medicines, tests or laboratory services are separate?", "What storage or future-transfer fees may apply?", "What is the cancellation or refund policy?", "When are payments due?"] },
      { heading: "Questions about success information", paragraphs: ["Ask whether figures refer to pregnancy or live birth, which age group, which treatment type, which denominator and how many cycles. Then ask what information from your own assessment matters most."] },
      { heading: "Questions about communication", paragraphs: ["Know who to call with medication questions, urgent symptoms, emotional concerns and administrative issues. Ask how quickly messages are usually answered and what counts as an emergency."] },
    ],
    faq: [{ question: "Do I need to ask all 15 questions at once?", answer: "No. Mark the questions most important to your immediate decision and take the rest to later appointments." }, { question: "Can I take notes?", answer: "Yes. You may also ask whether a written summary or permission to record explanations is available." }],
    sources: [coreSources.hfeaRates, coreSources.who],
  },
];
